# Generated by Django 4.2.3 on 2025-01-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_simulation', '0003_alter_order_product_id_alter_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
